import pyautogui

pyautogui.PAUSE = 1
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')
pyautogui.write('te amo')
pyautogui.press('enter')